spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/skillbox}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

services.openedx.host-header=${OPENEDX_HOST_HEADER:mamochki}
services.openedx.auth-token=${OPENEDX_AUTH_TOKEN:}
services.openedx.base-url=${OPENEDX_BASE_URL:http://localhost:18000}
services.openedx.default-password=${OPENEDX_DEFAULT_PASSWORD:Lab1Pass_2026}
services.openedx.enrollment-mode=${OPENEDX_ENROLLMENT_MODE:audit}

server.port=${PORT:8080}

# RabbitMQ AMQP 1.0 connection (Apache Qpid JMS)
# Требует: rabbitmq-plugins enable rabbitmq_amqp1_0
rabbitmq.amqp.url=${RABBITMQ_AMQP_URL:amqp://guest:guest@localhost:5672}

# Quartz Scheduler
spring.quartz.job-store-type=memory
spring.quartz.overwrite-existing-jobs=true
